config/routes.rb
Gb::Application.routes.draw do

  get "guest_book/index"
  get "guest_book/byguest"
  match "guest_book/submit" => "guest_book#submit", :via => :post
  match "guest_book" => "guest_book#index"

  resources :guests
  resource :guest_session

  match "guest/register" => "guests#new"

# match "guests/login" => "guest_sessions#new"
# match "guests/logout" => "guest_sessions#destroy"
  match "login" => "guest_sessions#new"
  match "logout" => "guest_sessions#destroy"

  #match "guest/show" => 'guest_book#index'

  root :to => 'guest_book#index'

end

app/models/guest.rb
class Guest < ActiveRecord::Base
  acts_as_authentic
  has_many :posts
  attr_accessible :username, :name, :location, :email
  attr_accessible :password, :password_confirmation

  def last_login_at
  end
end

app/models/guest_session.rb
class GuestSession < Authlogic::Session::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :guest
  attr_accessible :title, :body

  def author
    guest.nil? ? 'unknown' : guest.name
  end

  def username
    guest.nil? ? "" : guest.username
  end

  def self.byusername(username)
    joins(:guest).where('guests.username' => username)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper :all
  helper_method :current_guest_session, :current_guest
  protect_from_forgery
  
  private

  def current_guest_session
    return @current_guest_session if defined?(@current_guest_session)
    @current_guest_session = GuestSession.find
  end
    
  def current_guest
    return @current_guest if defined?(@current_guest)
    @current_guest = current_guest_session && current_guest_session.record
  end
    
  def require_guest
    unless current_guest
      store_location
      flash[:notice] = "You must be logged in to access this page"
      redirect_to new_guest_session_url
      return false
    end
  end

  def require_no_guest
    if current_guest
      store_location
      flash[:notice] = "You must be logged out to access this page"
      redirect_to :controller => "guest_book"
      return false
    end
  end
    
  def store_location
    session[:return_to] = request.fullpath
  end
    
  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end

end

app/controllers/guest_book_controller.rb
class GuestBookController < ApplicationController
  def index
    # FIXME: .order is not available w/Post.all, use workaround for the moment
    @posts = Post.where('1=1').order(:updated_at).reverse_order.page params[:page]
  end

  def byguest
    username = params[:username]
    return redirect_to :action=>"index" if username.nil? || username.empty?

    @user = Guest.find_by_username(username)
    # TODO: flash message
    return redirect_to :action=>"index" if @user.nil?

    @posts = Post.byusername(params[:username]).page params[:page]
  end

  def submit
    title = params[:title]
    body = params[:post]
    post = Post.new
    post.assign_attributes({ :title => title, :body => body})
    post.guest = current_guest
    post.save
    return redirect_to :action=>"index"
  end
end

app/controllers/guest_sessions_controller.rb
class GuestSessionsController < ApplicationController
  before_filter :require_no_guest, :only => [:new, :create]
  before_filter :require_guest, :only => :destroy

  def new
    @guest_session = GuestSession.new
  end

  def create
    @guest_session = GuestSession.new(params[:guest_session])
    if @guest_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default guest_book_index_url
    else
      render :action => :new
    end
  end

  def destroy # logout
    current_guest_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default guest_book_index_url
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  before_filter :require_guest, :only => [:index, :show, :edit, :update, :destroy]
  before_filter :require_no_guest, :only => [:new, :create]

  # GET /guests
  def index
    @guests = Guest.all
  end

  # GET /guests/:id
  def show
    @guest = Guest.find(params[:id])
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/:id/edit
  def edit 
    @guest = Guest.find(params[:id])
  end

  # POST /guests
  def create
    @guest = Guest.new(params[:guest])
    if @guest.save
      flash[:notice] = "Guest registered!"
      #redirect_to :controller => "guest_book", :action => "index"
      redirect_back_or_default guest_book_index_url
    else
      render :action => :new
    end
  end

  # PUT /guests/:id
  def update
    @guest = Guest.find(params[:id])
    if @guest.update_attributes(params[:guest])
      flash[:notice] = "Guest updated!"
      #redirect_to :controller => "guest_book", :action => "index"
      redirect_to guest_url
    else
      render :action => :edit
    end
  end

  # DELETE /guests/:id
  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy
    redirect_to guests_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guest_book_helper.rb
module GuestBookHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guest_book/_form.html.erb
<div class="post form">
  <div class="guest-block">
    <div class="post-author"><%= guest.name %></div>
    <div class="post-date">(your next message)</div>
  </div>

  <%= form_tag 'submit', :id => 'message-form' do %>

    <%= text_field_tag "title", "", :size => 42, :maxlength => 140 -%>
    <span class="poor-label">(title)</span>
    <br/>

    <%= text_area_tag(:post, "", :cols => '40%', :rows => 10) -%>
    <br/>

    <%= submit_tag "Submit" %>

  <% end %>
</div>

app/views/guest_book/_posts.html.erb
<%= paginate @posts %>
<div id="guestbook">
<% @posts.each do |post| %>
    <div class="post">
      <div class="guest-block">
        <div class="post-author">
           <% author = post.author
              if author.nil? || author == 'unknown' %>
                unknown
           <% else %>
                <%= link_to author, {:action => 'byguest', :username => post.username} %>
           <% end %>
        </div>
        <div class="post-date"><%= post.updated_at %></div>
      </div>
      <div class="message-block">
        <div class="post-title"><%= post.title %></div>
        <div class="post-body"><%= post.body %></div>
      </div>
    </div>
<% end %>
</div>

app/views/guest_book/byguest.html.erb
<h1>Guest Book for <%= @user.name %></h1>

<%= link_to 'see all users', { :action => 'index' } %>
<%= render :partial => "posts", :locals => { :posts => @posts } %>

app/views/guest_book/index.html.erb
<% if !current_guest.nil? %>
  <%= render :partial => "form", :locals => { :guest => current_guest } %>
<% end %>

<%= render :partial => "posts", :locals => { :posts => @posts } %>

app/views/guest_book/submit.html.erb
<h1>GuestBook#submit</h1>
<p>Find me in app/views/guest_book/submit.html.erb</p>

app/views/guest_sessions/new.html.erb
<h1>Login</h1>

<%= form_for @guest_session, :url => guest_session_path do |f| %>
  <%= render "shared/error_messages", :target => @guest_session %>

  <%= f.label :username %><br />
  <%= f.text_field :username %><br />
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.check_box :remember_me %><%= f.label :remember_me %><br />
  <br />
  <%= f.submit "Login" %>
<% end %>

app/views/guests/_form.html.erb
<%= form_for(@guest, :url => guest_path, :method => :post) do |f| %>

  <!-- TODO: error messages go here -->
 
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
  <div class="actions">
    <%= f.submit "Register" %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing guest profile</h1>

<p><%= notice %></p>

<div id="edit-guest">

  <%= form_for @guest, :url => guest_path do |f| %>

    <div class="field">
      <span class="field-label"><%= f.label :username %></span>
      <span class="field-value"><%= f.text_field :username %></span>
    </div>
    <div class="field">
      <span class="field-label"><%= f.label :name %></span>
      <span class="field-value"><%= f.text_field :name %></span>
    </div>
    <div class="field">
      <span class="field-label"><%= f.label :location %></span>
      <span class="field-value"><%= f.text_field :location %></span>
    </div>
    <div class="field">
      <span class="field-label"><%= f.label :email %></span>
      <span class="field-value"><%= f.text_field :email %></span>
    </div>

    <div class="field">
      <span class="field-label"><%= f.label :password %></span>
      <span class="field-value"><%= f.password_field :password %></span>
    </div>

    <div class="field">
      <span class="field-label"><%= f.label :password_confirmation, 'Confirmation' %></span>
      <span class="field-value"><%= f.password_field :password_confirmation %></span>
    </div>


    <div class="actions">
      <span class="field-label">&nbsp;</span>
      <span class="field-value"><%= f.submit "Update" %></span>
    </div>
  <% end %>
</div>

<!--
  <div class="tool-button"><%= link_to 'Done', guest_path(@guest) %></div>
-->

<!-- ---- -->


<!--

  <div class="field"><span class="field-name">Username:</span><span class="field-value"><%=h @guest.username %></span></div>
  <div class="field"><span class="field-name">Name:</span><span class="field-value"><%=h @guest.name %></span></div>
  <div class="field"><span class="field-name">Email:</span><span class="field-value"><%=h @guest.email %></span></div>
  <div class="field"><span class="field-name">Location:</span><span class="field-value"><%=h @guest.location %></span></div>

-->

app/views/guests/index.html.erb
<h1>Listing guests</h1>

<% if !@guest.nil? %>
  <%= render "shared/error_messages", :target => @guest %>
<% end %>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guests.each do |guest| %>
  <tr>
    <td><%= guest.email %></td>
    <td><%= link_to 'Show', guest %></td>
    <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
    <td><%= link_to 'Destroy', guest, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/guests/new.html.erb
<h1>Register</h1>

<%= render "shared/error_messages", :target => @guest %>

<%= form_for @guest, :url => { :action => "create" } do |f| %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
  <div class="actions">
    <%= f.submit "Register" %>
  </div>
<% end %>

app/views/guests/show.html.erb
<h1>Guest profile</h1>

<p><%= notice %></p>

<div id="show-guest">

  <div class="field">
    <span class="field-label">Username:</span>
    <span class="field-value"><%=h @guest.username %></span>
  </div>
  <div class="field">
    <span class="field-label">Name:</span>
    <span class="field-value"><%=h @guest.name %></span>
  </div>
  <div class="field">
    <span class="field-label">Email:</span>
    <span class="field-value"><%=h @guest.email %></span>
  </div>
  <div class="field">
    <span class="field-label">Location:</span>
    <span class="field-value"><%=h @guest.location %></span>
  </div>

  <div class="tool-button"><%= link_to 'Edit', edit_guest_path(@guest) %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="topnav">
  <span id="topnav-logo" class="left">
    <%= link_to "GB Guestbook", :controller=>"guest_book", :action=>"index" %>
  </span>
  <span id="topnav-guest" class="right">
    <% if !current_guest.nil? %>
      <%= link_to current_guest.username, {:controller => 'guests', :action => 'show', :id => current_guest.id} %> <span class="email">(<%= current_guest.email %>)</span> |
      <%= link_to "Logout", logout_url %>
    <% else %>
      <%= link_to_unless_current "Register", new_guest_path %> |
      <%= link_to "Login", login_url %>
    <% end %>
  </span>
</div>

<div id="container">
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div id="errorExplanation">
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>